version: '3.9'

services:
    php-fpm:
        build:
            context: .
            dockerfile: ./docker/php-fpm/Dockerfile
        depends_on:
            - postgres

    node:
        build:
            context: .
            dockerfile: ./docker/node/Dockerfile

    nginx:
        image: nginx:1.21-alpine
        depends_on:
            - php-fpm

    postgres:
        image: postgres:13.6-alpine
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - database:/var/lib/postgresql/data:rw

volumes:
    database:
