version: '3.9'

services:
    php-fpm:
        build:
            context: .
            dockerfile: ./docker/php-fpm/Dockerfile

    node:
        build:
            context: .
            dockerfile: ./docker/node/Dockerfile
